create table if not exists category
(
    id      bigint generated by default as identity not null,
    name    varchar(50)                             not null,
    ordinal integer                                 not null,
    constraint pk_category primary key (id)
);

create table if not exists ingredient
(
    id   bigint generated by default as identity not null,
    name varchar(50)                             not null,
    constraint pk_ingredient primary key (id)
);

create table if not exists recipe
(
    id          bigint generated by default as identity not null,
    title       varchar(50)                             not null,
    description varchar(100),
    prep_time   integer,
    cook_time   integer,
    servings    integer,
    instructions  TEXT                                  not null,
    difficulty  varchar(255)                            not null,
    health_label varchar(255),
    category_id bigint,
    constraint pk_recipe primary key (id)
);

create table if not exists recipe_ingredient
(
    recipe_id     bigint  not null,
    ingredient_id bigint  not null,
    amount        decimal not null,
    unit_id       bigint,
    constraint pk_recipe_ingredient primary key (recipe_id, ingredient_id)
);

create table if not exists unit
(
    id   bigint generated by default as identity not null,
    name varchar(50)                             not null,
    constraint pk_unit primary key (id)
);

alter table category
    add constraint uc_category_name unique (name);

alter table ingredient
    add constraint uc_ingredient_name unique (name);

alter table unit
    add constraint uc_unit_name unique (name);

alter table recipe_ingredient
    add constraint fk_recipe_ingredient_on_ingredient foreign key (ingredient_id) references ingredient (id);

alter table recipe_ingredient
    add constraint fk_recipe_ingredient_on_recipe foreign key (recipe_id) references recipe (id);

alter table recipe_ingredient
    add constraint fk_recipe_ingredient_on_unit foreign key (unit_id) references unit (id);

alter table recipe
    add constraint fk_recipe_on_category foreign key (category_id) references category (id);
