insert into public.category ("name", "ordinal")
values ('Main Course', 1),
       ('Side Dish', 2),
       ('Dessert', 3),
       ('Appetizer', 4),
       ('Salad', 5),
       ('Bread', 6),
       ('Breakfast', 7),
       ('Soup', 8),
       ('Beverage', 9),
       ('Sauce', 10),
       ('Marinade', 11),
       ('Fingerfood', 12),
       ('Snack', 13),
       ('Drink', 14);
