insert into public.ingredient ("name")
values ('Cream'),
       ('Yoghurt'),
       ('Milk'),
       ('Egg'),
       ('Sunflower Oil'),
       ('Peanut Oil'),
       ('Cacao'),
       ('Sugar'),
       ('Almonds'),
       ('Cashew Nuts'),
       ('Chicken Breast'),
       ('Beef'),
       ('Minced Meat'),
       ('Salmon'),
       ('Honey'),
       ('Kidney Beans'),
       ('White Beans'),
       ('Lentils'),
       ('Pasta'),
       ('Rice'),
       ('Tomatoes'),
       ('Cucumber'),
       ('Eggplant'),
       ('Garlic'),
       ('Onion'),
       ('Leek'),
       ('Spinach'),
       ('Chili'),
       ('Ginger'),
       ('Mushrooms'),
       ('Potatoes'),
       ('Peas'),
       ('Root Celery'),
       ('Carrots'),
       ('Zucchini'),
       ('Bell Pepper'),
       ('Savoy Cabbage'),
       ('Kohlrabi'),
       ('Celery'),
       ('Avocado'),
       ('Thyme'),
       ('Rosemary'),
       ('Dill'),
       ('Mint'),
       ('Orange'),
       ('Lemon'),
       ('Mango'),
       ('Blueberries'),
       ('Raspberries'),
       ('Strawberries');
